"""16_add_role_from_user_identities_table

Revision ID: 3a9267b83b3a
Revises: 15817c35613e
Create Date: 2026-09-06 01:42:19.585459

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a9267b83b3a"
down_revision: str | Sequence[str] | None = "15817c35613e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_identities",
        sa.Column(
            "role",
            sa.Enum(
                "SYSTEM_ADMIN",
                "DIRECTOR",
                "TEACHER",
                "STUDENT",
                "GUARDIAN",
                name="userrole",
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "uix_non_student_unique_phone",
        "user_identities",
        ["phone_number"],
        unique=True,
        postgresql_where=sa.text("role <> 'STUDENT'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix_non_student_unique_phone",
        table_name="user_identities",
        postgresql_where=sa.text("role <> 'STUDENT'"),
    )
    op.drop_column("user_identities", "role")
    # ### end Alembic commands ###
