"""26_remove_incorrect_idempotency_records_unique_constraint

Revision ID: 9a0c654d1f09
Revises: e9118ffea98d
Create Date: 2026-09-13 20:38:10.623421

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a0c654d1f09"
down_revision: str | Sequence[str] | None = "e9118ffea98d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uix_idempotency_key"), "idempotency_records", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uix_idempotency_key"),
        "idempotency_records",
        ["key"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
