"""11_remove_scheduled_for_field_from_emails_table

Revision ID: 792605b16afc
Revises: 81e1247bfbe8
Create Date: 2026-08-31 11:32:51.451177

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "792605b16afc"
down_revision: str | Sequence[str] | None = "81e1247bfbe8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emails", "scheduled_for")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "emails",
        sa.Column(
            "scheduled_for",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
