"""17_make_role_required_in_user_identities

Revision ID: ce1de058a2eb
Revises: 3a9267b83b3a
Create Date: 2026-09-06 01:45:51.152228

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce1de058a2eb"
down_revision: str | Sequence[str] | None = "3a9267b83b3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_identities",
        "role",
        existing_type=postgresql.ENUM(
            "SYSTEM_ADMIN",
            "DIRECTOR",
            "TEACHER",
            "STUDENT",
            "GUARDIAN",
            name="userrole",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_identities",
        "role",
        existing_type=postgresql.ENUM(
            "SYSTEM_ADMIN",
            "DIRECTOR",
            "TEACHER",
            "STUDENT",
            "GUARDIAN",
            name="userrole",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
