"""08_create_login_history_tables

Revision ID: 2a083220f6a9
Revises: c77787fce36d
Create Date: 2026-08-29 09:17:26.796166

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a083220f6a9"
down_revision: str | Sequence[str] | None = "c77787fce36d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_history",
        sa.Column("credentials_id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credentials_id"], ["user_credentials.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_history_credentials_id"),
        "login_history",
        ["credentials_id"],
        unique=False,
    )
    op.create_table(
        "login_history_summary",
        sa.Column("credentials_id", sa.Integer(), nullable=False),
        sa.Column("summary_date", sa.Date(), nullable=False),
        sa.Column("successful_logins", sa.Integer(), nullable=False),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credentials_id"], ["user_credentials.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "credentials_id", "summary_date", name="uix_login_summary_per_day"
        ),
    )
    op.create_index(
        op.f("ix_login_history_summary_credentials_id"),
        "login_history_summary",
        ["credentials_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_login_history_summary_credentials_id"),
        table_name="login_history_summary",
    )
    op.drop_table("login_history_summary")
    op.drop_index(op.f("ix_login_history_credentials_id"), table_name="login_history")
    op.drop_table("login_history")
    # ### end Alembic commands ###
