"""23_make_user_credentials_role_field_non_nullable

Revision ID: a8e5874d206b
Revises: 0fd1319c10ad
Create Date: 2026-09-07 12:59:07.464899

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a8e5874d206b"
down_revision: str | Sequence[str] | None = "0fd1319c10ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_credentials",
        "role",
        existing_type=postgresql.ENUM(
            "SYSTEM_ADMIN",
            "DIRECTOR",
            "TEACHER",
            "STUDENT",
            "GUARDIAN",
            name="userrole",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_credentials",
        "role",
        existing_type=postgresql.ENUM(
            "SYSTEM_ADMIN",
            "DIRECTOR",
            "TEACHER",
            "STUDENT",
            "GUARDIAN",
            name="userrole",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
