"""12_add_device_id_field_to_user_sessions_table

Revision ID: 73618d320c38
Revises: 792605b16afc
Create Date: 2026-09-02 11:40:03.920603

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73618d320c38"
down_revision: str | Sequence[str] | None = "792605b16afc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sessions", sa.Column("device_id", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_user_sessions_device_id"), "user_sessions", ["device_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_sessions_device_id"), table_name="user_sessions")
    op.drop_column("user_sessions", "device_id")
    # ### end Alembic commands ###
