"""02_create_user_credentials_table

Revision ID: 9e999f2ad82a
Revises: 0ba2136fc84f
Create Date: 2026-08-29 08:36:58.277313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e999f2ad82a"
down_revision: str | Sequence[str] | None = "0ba2136fc84f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "user_credentials",
        sa.Column("identity_id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "SYSTEM_ADMIN",
                "DIRECTOR",
                "TEACHER",
                "STUDENT",
                "GUARDIAN",
                name="userrole",
            ),
            nullable=False,
        ),
        sa.Column(
            "account_type",
            sa.Enum("STUDENT", "WORK", "PERSONAL", name="accounttype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PENDING_ACTIVATION",
                "DEACTIVATED",
                "DELETED",
                "PENDING_DELETION",
                "GRADUATED",
                "WITHDRAWN",
                "EXPELLED",
                name="userstatus",
            ),
            nullable=False,
        ),
        sa.Column("deletion_scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "pre_deletion_status",
            sa.Enum(
                "ACTIVE",
                "PENDING_ACTIVATION",
                "DEACTIVATED",
                "DELETED",
                "PENDING_DELETION",
                "GRADUATED",
                "WITHDRAWN",
                "EXPELLED",
                name="userstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"], ["user_identities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        "ix_gin_credentials_email",
        "user_credentials",
        ["email"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"email": "gin_trgm_ops"},
    )
    op.create_index(
        "uix_non_student_unique_email",
        "user_credentials",
        ["email"],
        unique=True,
        postgresql_where=sa.text("account_type != 'STUDENT'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix_non_student_unique_email",
        table_name="user_credentials",
        postgresql_where=sa.text("account_type != 'STUDENT'"),
    )
    op.drop_index(
        "ix_gin_credentials_email",
        table_name="user_credentials",
        postgresql_using="gin",
        postgresql_ops={"email": "gin_trgm_ops"},
    )
    op.drop_table("user_credentials")
    # ### end Alembic commands ###
