"""09_add_partial_index_to_user_credentials_for_personal_accounts

Revision ID: e42607716574
Revises: 2a083220f6a9
Create Date: 2026-08-29 18:41:05.721622

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e42607716574"
down_revision: str | Sequence[str] | None = "2a083220f6a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uix_one_personal_account_per_identity",
        "user_credentials",
        ["identity_id"],
        unique=True,
        postgresql_where=sa.text("account_type = 'PERSONAL'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix_one_personal_account_per_identity",
        table_name="user_credentials",
        postgresql_where=sa.text("account_type = 'PERSONAL'"),
    )
    # ### end Alembic commands ###
