"""07_create_user_email_changes_table

Revision ID: c77787fce36d
Revises: 22ccdaf9639f
Create Date: 2026-08-29 09:09:30.738071

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c77787fce36d"
down_revision: str | Sequence[str] | None = "22ccdaf9639f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_email_changes",
        sa.Column("credentials_id", sa.Integer(), nullable=False),
        sa.Column("new_email", sa.String(length=100), nullable=False),
        sa.Column("email_change_token_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "email_change_token_expires_at", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credentials_id"], ["user_credentials.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credentials_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_email_changes")
    # ### end Alembic commands ###
