"""21_delete_user_identities_role_field

Revision ID: 033e0ceba1e6
Revises: ad6836e076e6
Create Date: 2026-09-07 12:50:30.795902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "033e0ceba1e6"
down_revision: str | Sequence[str] | None = "ad6836e076e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_identities", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_identities",
        sa.Column(
            "role",
            postgresql.ENUM(
                "SYSTEM_ADMIN",
                "DIRECTOR",
                "TEACHER",
                "STUDENT",
                "GUARDIAN",
                name="userrole",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
