"""22_add_role_field_to_user_credentials_table

Revision ID: 0fd1319c10ad
Revises: 033e0ceba1e6
Create Date: 2026-09-07 12:55:51.518116

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fd1319c10ad"
down_revision: str | Sequence[str] | None = "033e0ceba1e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_credentials",
        sa.Column(
            "role",
            sa.Enum(
                "SYSTEM_ADMIN",
                "DIRECTOR",
                "TEACHER",
                "STUDENT",
                "GUARDIAN",
                name="userrole",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_credentials", "role")
    # ### end Alembic commands ###
