"""24_rename_emails_body_html_field

Revision ID: e946e34303dc
Revises: a8e5874d206b
Create Date: 2026-09-07 13:14:25.844845

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e946e34303dc"
down_revision: str | Sequence[str] | None = "a8e5874d206b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "emails",
        "body_html",
        new_column_name="html_body",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "emails",
        "html_body",
        new_column_name="body_html",
    )
    # ### end Alembic commands ###
