"""03_create_user_activations_table

Revision ID: c3336b6ca51e
Revises: 9e999f2ad82a
Create Date: 2026-08-29 08:49:58.179772

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3336b6ca51e"
down_revision: str | Sequence[str] | None = "9e999f2ad82a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activations",
        sa.Column("credentials_id", sa.Integer(), nullable=False),
        sa.Column("activation_token_hash", sa.String(), nullable=False),
        sa.Column(
            "activation_token_expires_at", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credentials_id"], ["user_credentials.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credentials_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_activations")
    # ### end Alembic commands ###
