"""01_create_user_identities_table

Revision ID: 0ba2136fc84f
Revises:
Create Date: 2026-08-29 08:29:23.749368

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ba2136fc84f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "user_identities",
        sa.Column("firstname", sa.String(length=50), nullable=False),
        sa.Column("lastname", sa.String(length=50), nullable=False),
        sa.Column("middlename", sa.String(length=50), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("address", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=25), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_gin_identity_firstname",
        "user_identities",
        ["firstname"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"firstname": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_gin_identity_lastname",
        "user_identities",
        ["lastname"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"lastname": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_gin_identity_lastname",
        table_name="user_identities",
        postgresql_using="gin",
        postgresql_ops={"lastname": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_gin_identity_firstname",
        table_name="user_identities",
        postgresql_using="gin",
        postgresql_ops={"firstname": "gin_trgm_ops"},
    )
    op.drop_table("user_identities")
    # ### end Alembic commands ###
