"""10_create_emails_table

Revision ID: 81e1247bfbe8
Revises: e42607716574
Create Date: 2026-08-30 10:09:16.777205

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81e1247bfbe8"
down_revision: str | Sequence[str] | None = "e42607716574"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emails",
        sa.Column("recipient_email", sa.String(length=100), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column(
            "email_type",
            sa.Enum(
                "ACTIVATION",
                "UPDATING_ACCOUNT",
                "ADMIN_CREDENTIALS_OVERRIDE",
                "ACCOUNT_DEACTIVATION",
                "ACCOUNT_ACTIVATION",
                "PASSWORD_RESET_ADMIN",
                "EMAIL_CHANGE_CODE",
                "EMAIL_CHANGED",
                "PASSWORD_CHANGED",
                "FORGOT_PASSWORD",
                name="emailtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", name="emailstatus"),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "scheduled_for",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column("triggered_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"], ["user_credentials.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emails_email_type"), "emails", ["email_type"], unique=False
    )
    op.create_index(op.f("ix_emails_status"), "emails", ["status"], unique=False)
    op.create_index(
        op.f("ix_emails_triggered_by"), "emails", ["triggered_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_emails_triggered_by"), table_name="emails")
    op.drop_index(op.f("ix_emails_status"), table_name="emails")
    op.drop_index(op.f("ix_emails_email_type"), table_name="emails")
    op.drop_table("emails")
    # ### end Alembic commands ###
