"""27_add_correct_idempotency_records_unique_constraint

Revision ID: 0c3df63ccc72
Revises: 9a0c654d1f09
Create Date: 2026-09-13 20:40:34.402412

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c3df63ccc72"
down_revision: str | Sequence[str] | None = "9a0c654d1f09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_idempotency_operation_actor_key",
        "idempotency_records",
        ["operation", "actor_id", "key"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uix_idempotency_operation_actor_key", "idempotency_records", type_="unique"
    )
    # ### end Alembic commands ###
