"""15_remove_role_from_user_credentials_table

Revision ID: 15817c35613e
Revises: 21bf6cb4c22e
Create Date: 2026-09-06 01:40:02.043958

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "15817c35613e"
down_revision: str | Sequence[str] | None = "21bf6cb4c22e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_credentials", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_credentials",
        sa.Column(
            "role",
            postgresql.ENUM(
                "SYSTEM_ADMIN",
                "DIRECTOR",
                "TEACHER",
                "STUDENT",
                "GUARDIAN",
                name="userrole",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
