"""20_delete_user_identities_phonenumber_partial_index

Revision ID: ad6836e076e6
Revises: c97ac6026f3e
Create Date: 2026-09-07 12:48:21.442051

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad6836e076e6"
down_revision: str | Sequence[str] | None = "c97ac6026f3e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uix_non_student_unique_phone"),
        table_name="user_identities",
        postgresql_where="(role <> 'STUDENT'::userrole)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("uix_non_student_unique_phone"),
        "user_identities",
        ["phone_number"],
        unique=True,
        postgresql_where="(role <> 'STUDENT'::userrole)",
    )
    # ### end Alembic commands ###
