"""29_rename_user_credentials_pre_deletion_status_field

Revision ID: 7b56ec270c21
Revises: 1a14e6136053
Create Date: 2026-10-01 14:31:22.471802

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b56ec270c21"
down_revision: str | Sequence[str] | None = "1a14e6136053"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_credentials",
        "pre_deletion_status",
        new_column_name="pre_transition_status",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_credentials",
        "pre_transition_status",
        new_column_name="pre_deletion_status",
    )
    # ### end Alembic commands ###
