"""06_create_user_password_resets_table

Revision ID: 22ccdaf9639f
Revises: 74e8d0f9f15c
Create Date: 2026-08-29 09:04:29.777889

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22ccdaf9639f"
down_revision: str | Sequence[str] | None = "74e8d0f9f15c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_password_resets",
        sa.Column("credentials_id", sa.Integer(), nullable=False),
        sa.Column("reset_password_token_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "reset_password_token_expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credentials_id"], ["user_credentials.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credentials_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_password_resets")
    # ### end Alembic commands ###
