"""28_add_index_to_expires_at_in_idempotency_records_table

Revision ID: 1a14e6136053
Revises: 0c3df63ccc72
Create Date: 2026-09-13 20:42:16.529747

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a14e6136053"
down_revision: str | Sequence[str] | None = "0c3df63ccc72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_idempotency_records_expires_at"),
        "idempotency_records",
        ["expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_idempotency_records_expires_at"), table_name="idempotency_records"
    )
    # ### end Alembic commands ###
